# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default
  demands:
  - Agent.Name -equals ZURI

steps:
# Instalar Node
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: "Instalar Node.js"

# Instalar dependencias
- script: npm install
  displayName: "Instalar dependencias"

# Ejecutar build de Vite
- script: npm run build
  displayName: "Build del Frontend"

# Publicar artefactos (carpeta dist)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'frontend-dist'
    publishLocation: 'Container'
  displayName: "Publicar Artefactos del Frontend"

